package cmpt276.kzcheng.asn2;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main class for the Spring Boot application. Used to start the application. Automatically generated by Spring Boot.
 */
@SpringBootApplication
public class Asn2Application {
	public static void main(String[] args) {
		SpringApplication.run(Asn2Application.class, args);
	}
}
