package cmpt276.kzcheng.asn2;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Automated testing system automatically generated by Spring Boot. 
 * 
 * Automated testing is out of the scope of this project. So this is being left empty.
 */
@SpringBootTest
class asn2ApplicationTests {
	@Test
	void contextLoads() {}
}
